export const PERMISSIONS = {
  USERS: {
    VIEW: "users.view",
    CREATE: "users.create",
    UPDATE: "users.update",
    DELETE: "users.delete",
  },
  ROLES: {
    VIEW: "roles.view",
    MANAGE: "roles.manage",
  },
  SETTINGS: {
    COMPANY_VIEW: "settings.company.view",
    COMPANY_UPDATE: "settings.company.update",
    BRANCH_MANAGE: "settings.branch.manage",
    WAREHOUSE_MANAGE: "settings.warehouse.manage",
    TAX_MANAGE: "settings.tax.manage",
    RECEIPT_MANAGE: "settings.receipt.manage",
    FISCAL_MANAGE: "settings.fiscal.manage",
  },
  PRODUCTS: {
    VIEW: "products.view",
    CREATE: "products.create",
    UPDATE: "products.update",
    DELETE: "products.delete",
  },
  CATEGORIES: { MANAGE: "categories.manage" },
  BRANDS: { MANAGE: "brands.manage" },
  UNITS: { MANAGE: "units.manage" },
  BARCODE: {
    GENERATE: "barcode.generate",
    PRINT: "barcode.print",
  },
  INVENTORY: {
    VIEW: "inventory.view",
    STOCK_IN: "inventory.stock-in",
    STOCK_OUT: "inventory.stock-out",
    ADJUST: "inventory.adjust",
    TRANSFER: "inventory.transfer",
    STOCK_COUNT: "inventory.stock-count",
    LEDGER_VIEW: "inventory.ledger.view",
  },
  POS: {
    ACCESS: "pos.access",
    SALE_CREATE: "pos.sale.create",
    SALE_HOLD: "pos.sale.hold",
    SALE_DISCOUNT: "pos.sale.discount",
    SALE_DISCOUNT_UNLIMITED: "pos.sale.discount.unlimited",
    SALE_VOID: "pos.sale.void",
    SALE_REFUND: "pos.sale.refund",
    SALE_RETURN: "pos.sale.return",
    SALE_EXCHANGE: "pos.sale.exchange",
    RECEIPT_REPRINT: "pos.receipt.reprint",
    COUPON_APPLY: "pos.coupon.apply",
    GIFT_CARD_REDEEM: "pos.gift-card.redeem",
  },
  CASH_REGISTER: {
    OPEN: "cash-register.open",
    CLOSE: "cash-register.close",
    VIEW: "cash-register.view",
  },
  CUSTOMERS: {
    VIEW: "customers.view",
    MANAGE: "customers.manage",
    CREDIT_MANAGE: "customers.credit.manage",
    STATEMENT_VIEW: "customers.statement.view",
  },
  SUPPLIERS: {
    VIEW: "suppliers.view",
    MANAGE: "suppliers.manage",
    PAYMENT: "suppliers.payment",
    STATEMENT_VIEW: "suppliers.statement.view",
  },
  PURCHASING: {
    REQUEST_CREATE: "purchasing.request.create",
    REQUEST_APPROVE: "purchasing.request.approve",
    ORDER_CREATE: "purchasing.order.create",
    ORDER_APPROVE: "purchasing.order.approve",
    RECEIVE: "purchasing.receive",
    INVOICE_MANAGE: "purchasing.invoice.manage",
    RETURN: "purchasing.return",
  },
  ACCOUNTING: {
    COA_VIEW: "accounting.coa.view",
    COA_MANAGE: "accounting.coa.manage",
    JOURNAL_VIEW: "accounting.journal.view",
    JOURNAL_CREATE: "accounting.journal.create",
    JOURNAL_VOID: "accounting.journal.void",
    PERIOD_CLOSE: "accounting.period.close",
    BANK_MANAGE: "accounting.bank.manage",
    BANK_RECONCILE: "accounting.bank.reconcile",
    EXPENSE_CREATE: "accounting.expense.create",
    INCOME_CREATE: "accounting.income.create",
  },
  REPORTS: {
    DASHBOARD: "reports.dashboard",
    SALES: "reports.sales",
    PURCHASES: "reports.purchases",
    INVENTORY: "reports.inventory",
    FINANCIAL: "reports.financial",
    EXPORT: "reports.export",
  },
  AUDIT: { VIEW: "audit.view" },
  NOTIFICATIONS: { VIEW: "notifications.view" },
} as const;

type PermissionValues<T> = T extends Record<string, infer U>
  ? U extends string
    ? U
    : PermissionValues<U>
  : never;

export type Permission = PermissionValues<typeof PERMISSIONS>;

export const ALL_PERMISSION_CODES: Permission[] = Object.values(PERMISSIONS).flatMap(
  (group) => Object.values(group),
) as Permission[];

export interface PermissionDefinition {
  code: Permission;
  module: string;
  action: string;
  description: string;
}

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { code: "users.view", module: "users", action: "view", description: "View users" },
  { code: "users.create", module: "users", action: "create", description: "Create users" },
  { code: "users.update", module: "users", action: "update", description: "Update users" },
  { code: "users.delete", module: "users", action: "delete", description: "Delete users" },
  { code: "roles.view", module: "roles", action: "view", description: "View roles" },
  { code: "roles.manage", module: "roles", action: "manage", description: "Manage roles" },
  { code: "settings.company.view", module: "settings", action: "company.view", description: "View company settings" },
  { code: "settings.company.update", module: "settings", action: "company.update", description: "Update company settings" },
  { code: "settings.branch.manage", module: "settings", action: "branch.manage", description: "Manage branches" },
  { code: "settings.warehouse.manage", module: "settings", action: "warehouse.manage", description: "Manage warehouses" },
  { code: "settings.tax.manage", module: "settings", action: "tax.manage", description: "Manage tax rates" },
  { code: "settings.receipt.manage", module: "settings", action: "receipt.manage", description: "Manage receipt settings" },
  { code: "settings.fiscal.manage", module: "settings", action: "fiscal.manage", description: "Manage fiscal year" },
  { code: "products.view", module: "products", action: "view", description: "View products" },
  { code: "products.create", module: "products", action: "create", description: "Create products" },
  { code: "products.update", module: "products", action: "update", description: "Update products" },
  { code: "products.delete", module: "products", action: "delete", description: "Delete products" },
  { code: "categories.manage", module: "categories", action: "manage", description: "Manage categories" },
  { code: "brands.manage", module: "brands", action: "manage", description: "Manage brands" },
  { code: "units.manage", module: "units", action: "manage", description: "Manage units" },
  { code: "barcode.generate", module: "barcode", action: "generate", description: "Generate barcodes" },
  { code: "barcode.print", module: "barcode", action: "print", description: "Print barcode labels" },
  { code: "inventory.view", module: "inventory", action: "view", description: "View inventory" },
  { code: "inventory.stock-in", module: "inventory", action: "stock-in", description: "Stock in" },
  { code: "inventory.stock-out", module: "inventory", action: "stock-out", description: "Stock out" },
  { code: "inventory.adjust", module: "inventory", action: "adjust", description: "Adjust stock" },
  { code: "inventory.transfer", module: "inventory", action: "transfer", description: "Transfer stock" },
  { code: "inventory.stock-count", module: "inventory", action: "stock-count", description: "Stock count" },
  { code: "inventory.ledger.view", module: "inventory", action: "ledger.view", description: "View inventory ledger" },
  { code: "pos.access", module: "pos", action: "access", description: "Access POS" },
  { code: "pos.sale.create", module: "pos", action: "sale.create", description: "Create sales" },
  { code: "pos.sale.hold", module: "pos", action: "sale.hold", description: "Hold sales" },
  { code: "pos.sale.discount", module: "pos", action: "sale.discount", description: "Apply discounts" },
  { code: "pos.sale.discount.unlimited", module: "pos", action: "sale.discount.unlimited", description: "Unlimited discounts" },
  { code: "pos.sale.void", module: "pos", action: "sale.void", description: "Void sales" },
  { code: "pos.sale.refund", module: "pos", action: "sale.refund", description: "Refund sales" },
  { code: "pos.sale.return", module: "pos", action: "sale.return", description: "Return sales" },
  { code: "pos.sale.exchange", module: "pos", action: "sale.exchange", description: "Exchange sales" },
  { code: "pos.receipt.reprint", module: "pos", action: "receipt.reprint", description: "Reprint receipts" },
  { code: "pos.coupon.apply", module: "pos", action: "coupon.apply", description: "Apply coupons" },
  { code: "pos.gift-card.redeem", module: "pos", action: "gift-card.redeem", description: "Redeem gift cards" },
  { code: "cash-register.open", module: "cash-register", action: "open", description: "Open cash register" },
  { code: "cash-register.close", module: "cash-register", action: "close", description: "Close cash register" },
  { code: "cash-register.view", module: "cash-register", action: "view", description: "View cash register" },
  { code: "customers.view", module: "customers", action: "view", description: "View customers" },
  { code: "customers.manage", module: "customers", action: "manage", description: "Manage customers" },
  { code: "customers.credit.manage", module: "customers", action: "credit.manage", description: "Manage customer credit" },
  { code: "customers.statement.view", module: "customers", action: "statement.view", description: "View customer statements" },
  { code: "suppliers.view", module: "suppliers", action: "view", description: "View suppliers" },
  { code: "suppliers.manage", module: "suppliers", action: "manage", description: "Manage suppliers" },
  { code: "suppliers.payment", module: "suppliers", action: "payment", description: "Supplier payments" },
  { code: "suppliers.statement.view", module: "suppliers", action: "statement.view", description: "View supplier statements" },
  { code: "purchasing.request.create", module: "purchasing", action: "request.create", description: "Create purchase requests" },
  { code: "purchasing.request.approve", module: "purchasing", action: "request.approve", description: "Approve purchase requests" },
  { code: "purchasing.order.create", module: "purchasing", action: "order.create", description: "Create purchase orders" },
  { code: "purchasing.order.approve", module: "purchasing", action: "order.approve", description: "Approve purchase orders" },
  { code: "purchasing.receive", module: "purchasing", action: "receive", description: "Receive goods" },
  { code: "purchasing.invoice.manage", module: "purchasing", action: "invoice.manage", description: "Manage supplier invoices" },
  { code: "purchasing.return", module: "purchasing", action: "return", description: "Supplier returns" },
  { code: "accounting.coa.view", module: "accounting", action: "coa.view", description: "View chart of accounts" },
  { code: "accounting.coa.manage", module: "accounting", action: "coa.manage", description: "Manage chart of accounts" },
  { code: "accounting.journal.view", module: "accounting", action: "journal.view", description: "View journals" },
  { code: "accounting.journal.create", module: "accounting", action: "journal.create", description: "Create journals" },
  { code: "accounting.journal.void", module: "accounting", action: "journal.void", description: "Void journals" },
  { code: "accounting.period.close", module: "accounting", action: "period.close", description: "Close accounting period" },
  { code: "accounting.bank.manage", module: "accounting", action: "bank.manage", description: "Manage bank accounts" },
  { code: "accounting.bank.reconcile", module: "accounting", action: "bank.reconcile", description: "Bank reconciliation" },
  { code: "accounting.expense.create", module: "accounting", action: "expense.create", description: "Create expenses" },
  { code: "accounting.income.create", module: "accounting", action: "income.create", description: "Create income" },
  { code: "reports.dashboard", module: "reports", action: "dashboard", description: "View dashboard" },
  { code: "reports.sales", module: "reports", action: "sales", description: "Sales reports" },
  { code: "reports.purchases", module: "reports", action: "purchases", description: "Purchase reports" },
  { code: "reports.inventory", module: "reports", action: "inventory", description: "Inventory reports" },
  { code: "reports.financial", module: "reports", action: "financial", description: "Financial reports" },
  { code: "reports.export", module: "reports", action: "export", description: "Export reports" },
  { code: "audit.view", module: "audit", action: "view", description: "View audit logs" },
  { code: "notifications.view", module: "notifications", action: "view", description: "View notifications" },
];
