import {
  ALL_PERMISSION_CODES,
  PERMISSIONS,
  type Permission,
} from "./permissions";

export const SYSTEM_ROLES = {
  OWNER: "Owner",
  MANAGER: "Manager",
  ACCOUNTANT: "Accountant",
  CASHIER: "Cashier",
  WAREHOUSE: "Warehouse",
  VIEWER: "Viewer",
} as const;

export type SystemRoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

/** Privileges reserved for organization owners (not branch managers). */
const MANAGER_EXCLUDED: Permission[] = [
  PERMISSIONS.USERS.CREATE,
  PERMISSIONS.USERS.UPDATE,
  PERMISSIONS.USERS.DELETE,
  PERMISSIONS.ROLES.MANAGE,
  PERMISSIONS.SETTINGS.FISCAL_MANAGE,
  PERMISSIONS.ACCOUNTING.COA_MANAGE,
  PERMISSIONS.ACCOUNTING.JOURNAL_CREATE,
  PERMISSIONS.ACCOUNTING.JOURNAL_VOID,
  PERMISSIONS.ACCOUNTING.PERIOD_CLOSE,
  PERMISSIONS.ACCOUNTING.BANK_RECONCILE,
];

const ownerPermissions: Permission[] = [...ALL_PERMISSION_CODES];

const managerPermissions: Permission[] = ALL_PERMISSION_CODES.filter(
  (p) => !MANAGER_EXCLUDED.includes(p),
);

/** Finance: books, payables/receivables context, reporting. */
const accountantPermissions: Permission[] = [
  PERMISSIONS.SETTINGS.COMPANY_VIEW,
  PERMISSIONS.SETTINGS.TAX_MANAGE,
  PERMISSIONS.PRODUCTS.VIEW,
  PERMISSIONS.INVENTORY.VIEW,
  PERMISSIONS.INVENTORY.LEDGER_VIEW,
  PERMISSIONS.CUSTOMERS.VIEW,
  PERMISSIONS.CUSTOMERS.CREDIT_MANAGE,
  PERMISSIONS.CUSTOMERS.STATEMENT_VIEW,
  PERMISSIONS.SUPPLIERS.VIEW,
  PERMISSIONS.SUPPLIERS.PAYMENT,
  PERMISSIONS.SUPPLIERS.STATEMENT_VIEW,
  PERMISSIONS.PURCHASING.INVOICE_MANAGE,
  PERMISSIONS.ACCOUNTING.COA_VIEW,
  PERMISSIONS.ACCOUNTING.COA_MANAGE,
  PERMISSIONS.ACCOUNTING.JOURNAL_VIEW,
  PERMISSIONS.ACCOUNTING.JOURNAL_CREATE,
  PERMISSIONS.ACCOUNTING.JOURNAL_VOID,
  PERMISSIONS.ACCOUNTING.PERIOD_CLOSE,
  PERMISSIONS.ACCOUNTING.BANK_MANAGE,
  PERMISSIONS.ACCOUNTING.BANK_RECONCILE,
  PERMISSIONS.ACCOUNTING.EXPENSE_CREATE,
  PERMISSIONS.ACCOUNTING.INCOME_CREATE,
  PERMISSIONS.CASH_REGISTER.VIEW,
  PERMISSIONS.REPORTS.DASHBOARD,
  PERMISSIONS.REPORTS.SALES,
  PERMISSIONS.REPORTS.SALES_INVOICE_LIST,
  PERMISSIONS.REPORTS.SALES_RETURN_LIST,
  PERMISSIONS.REPORTS.PURCHASES,
  PERMISSIONS.REPORTS.INVENTORY,
  PERMISSIONS.REPORTS.FINANCIAL,
  PERMISSIONS.REPORTS.EXPORT,
  PERMISSIONS.AUDIT.VIEW,
  PERMISSIONS.NOTIFICATIONS.VIEW,
];

/** Front-of-house POS (no void / unlimited discount — those stay with Manager+). */
const cashierPermissions: Permission[] = [
  PERMISSIONS.PRODUCTS.VIEW,
  PERMISSIONS.POS.ACCESS,
  PERMISSIONS.POS.SALE_CREATE,
  PERMISSIONS.POS.SALE_HOLD,
  PERMISSIONS.POS.SALE_DISCOUNT,
  PERMISSIONS.POS.SALE_RETURN,
  PERMISSIONS.POS.SALE_REFUND,
  PERMISSIONS.POS.SALE_EXCHANGE,
  PERMISSIONS.POS.RECEIPT_REPRINT,
  PERMISSIONS.POS.COUPON_APPLY,
  PERMISSIONS.POS.GIFT_CARD_REDEEM,
  PERMISSIONS.CASH_REGISTER.OPEN,
  PERMISSIONS.CASH_REGISTER.CLOSE,
  PERMISSIONS.CASH_REGISTER.VIEW,
  PERMISSIONS.CUSTOMERS.VIEW,
  PERMISSIONS.CUSTOMERS.MANAGE,
  PERMISSIONS.BARCODE.PRINT,
  PERMISSIONS.NOTIFICATIONS.VIEW,
];

/**
 * Catalogue, stock, purchasing execution, warehouses, and branch assortment
 * (assortment is gated by products.update).
 */
const warehousePermissions: Permission[] = [
  PERMISSIONS.PRODUCTS.VIEW,
  PERMISSIONS.PRODUCTS.CREATE,
  PERMISSIONS.PRODUCTS.UPDATE,
  PERMISSIONS.CATEGORIES.MANAGE,
  PERMISSIONS.BRANDS.MANAGE,
  PERMISSIONS.UNITS.MANAGE,
  PERMISSIONS.BARCODE.GENERATE,
  PERMISSIONS.BARCODE.PRINT,
  PERMISSIONS.INVENTORY.VIEW,
  PERMISSIONS.INVENTORY.STOCK_IN,
  PERMISSIONS.INVENTORY.STOCK_OUT,
  PERMISSIONS.INVENTORY.ADJUST,
  PERMISSIONS.INVENTORY.TRANSFER,
  PERMISSIONS.INVENTORY.STOCK_COUNT,
  PERMISSIONS.INVENTORY.LEDGER_VIEW,
  PERMISSIONS.SETTINGS.WAREHOUSE_MANAGE,
  PERMISSIONS.SUPPLIERS.VIEW,
  PERMISSIONS.SUPPLIERS.MANAGE,
  PERMISSIONS.PURCHASING.REQUEST_CREATE,
  PERMISSIONS.PURCHASING.ORDER_CREATE,
  PERMISSIONS.PURCHASING.RECEIVE,
  PERMISSIONS.PURCHASING.INVOICE_MANAGE,
  PERMISSIONS.PURCHASING.RETURN,
  PERMISSIONS.REPORTS.DASHBOARD,
  PERMISSIONS.REPORTS.PURCHASES,
  PERMISSIONS.REPORTS.INVENTORY,
  PERMISSIONS.NOTIFICATIONS.VIEW,
];

/** Read-only operational and financial views. */
const viewerPermissions: Permission[] = [
  PERMISSIONS.SETTINGS.COMPANY_VIEW,
  PERMISSIONS.PRODUCTS.VIEW,
  PERMISSIONS.INVENTORY.VIEW,
  PERMISSIONS.INVENTORY.LEDGER_VIEW,
  PERMISSIONS.CUSTOMERS.VIEW,
  PERMISSIONS.CUSTOMERS.STATEMENT_VIEW,
  PERMISSIONS.SUPPLIERS.VIEW,
  PERMISSIONS.SUPPLIERS.STATEMENT_VIEW,
  PERMISSIONS.ACCOUNTING.COA_VIEW,
  PERMISSIONS.ACCOUNTING.JOURNAL_VIEW,
  PERMISSIONS.CASH_REGISTER.VIEW,
  PERMISSIONS.REPORTS.DASHBOARD,
  PERMISSIONS.REPORTS.SALES,
  PERMISSIONS.REPORTS.SALES_INVOICE_LIST,
  PERMISSIONS.REPORTS.SALES_RETURN_LIST,
  PERMISSIONS.REPORTS.PURCHASES,
  PERMISSIONS.REPORTS.INVENTORY,
  PERMISSIONS.REPORTS.FINANCIAL,
  PERMISSIONS.NOTIFICATIONS.VIEW,
];

export const ROLE_PERMISSION_MAP: Record<SystemRoleName, Permission[]> = {
  [SYSTEM_ROLES.OWNER]: ownerPermissions,
  [SYSTEM_ROLES.MANAGER]: managerPermissions,
  [SYSTEM_ROLES.ACCOUNTANT]: accountantPermissions,
  [SYSTEM_ROLES.CASHIER]: cashierPermissions,
  [SYSTEM_ROLES.WAREHOUSE]: warehousePermissions,
  [SYSTEM_ROLES.VIEWER]: viewerPermissions,
};

export const ROLE_DESCRIPTIONS: Record<SystemRoleName, string> = {
  [SYSTEM_ROLES.OWNER]:
    "Full system access (also granted automatically via organization ownership)",
  [SYSTEM_ROLES.MANAGER]:
    "Branch operations including POS void/unlimited discount; no user/role admin or sensitive accounting closes",
  [SYSTEM_ROLES.ACCOUNTANT]:
    "Accounting, tax, payables/receivables, and financial reports",
  [SYSTEM_ROLES.CASHIER]:
    "POS sales, limited discounts, cash register, and customers",
  [SYSTEM_ROLES.WAREHOUSE]:
    "Products, assortment, inventory, warehouses, and purchasing execution",
  [SYSTEM_ROLES.VIEWER]:
    "Read-only access to catalogue, stock, statements, and reports",
};
